name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar QEMU
      uses: docker/setup-qemu-action@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Convertir nombre de repositorio a minúsculas
      id: repo_name
      run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Construir y publicar imagen multi-arquitectura
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ghcr.io/${{ env.REPO_LC }}:latest
          ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
